### PR TITLE
Added the ability to vertically align content in row blocks

### LINKED ISSUE #374: Add ability to vertically align all the columns

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves #374 

Vertical alignment was enabled in Gutenberg core in a recent release
https://github.com/WordPress/gutenberg/pull/13989

This PR enables the vertical alignment toolbar for inner blocks inside of a row block.

https://cloudup.com/cxNfpe43_El

### Note

When an image is added to a row, the `resize

### CODE REVIEW

**Comment by richtabor** [comment]
@EvanHerman One additional bit we need to account for is if a user is running < Gutenberg 5.4 or < WordPress 5.2, neither of which have the `BlockVerticalAlignmentToolbar` component available.

Currently the editor breaks when you turn off the Gutenberg plugin and run this branch.

**Comment by paranoia1906** [comment]
Request on wp.org came in regarding this change. 

https://wordpress.org/support/topic/column-block-alignment/

**Comment by richtabor** [comment]
Yea but we can't merge this until WordPress 5.2 comes out :(

**Comment by AnthonyLedesma** [comment]
This PR was based on CoBlocks 1.9.2 and has a number of conflicts. Started new branch `vertical-align-row-block-53` but not getting the behavior that I expect on front end or in editor.

**Comment by richtabor** [comment]
Closing as the core Columns block supports this now, as well as most other Row block features.

**Pull request closed without merging**
