### PR TITLE
Bug fix for text color in Hero block

### PR DESCRIPTION
**Pull request by olafleur**
### Description
~This test had been skipped because of issue #1762 . However, now it seems to pass and I am not able to reproduce the problem in Go and TwentyTwenty.~

This is a suggested fix for #1762. I have now found the problem. See later in the thread.

### Types of changes
~Add a test~
Bug fix

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests

### CODE REVIEW

**Review by AnthonyLedesma — CHANGES_REQUESTED** [review]
Unfortunately, I am still able to reproduce this bug today in WordPress 5.7. Here is what I am seeing within Cypress.

image

Here is the interaction within the editor.
heroTextColor

**Comment by olafleur** [comment]
Oh! I was using 5.8-alpha-50427-src (development version).

**Comment by olafleur** [comment]
@AnthonyLedesma It should be fine now, classes for text color weren't properly added when rendering the block :)

In fact, at line 45, the text color classes that were set a few lines earlier were erased ;)

**Review by AnthonyLedesma — APPROVED** [review]
Great job here @olafleur. This issue is indeed fixed for new Hero blocks but it looks like block deprecations are needed here for blocks that had been configured with colors prior to your changes. I went ahead and pushed those changes up. LGTM.

You can test block deprecations by pasting this block markup within the editor.
```
<!-- wp:coblocks/hero {"textColor":"primary","coblocks":{"id":"224145629279"}} -->
<div class="wp-block-coblocks-hero alignfull coblocks-hero-224145629279"><div class="wp-block-coblocks-hero__inner hero-center-left-align has-padding has-huge-padding" style="min-height:500px"><div class="wp-block-coblocks-hero__content-wrapper"><div class="wp-block-coblocks-hero__content" style="max-width:560px"><!-- wp:heading {"placeholder":"Add hero heading…"} -->
<h2>test</h2>
<!-- /wp:heading --><!-- wp:paragraph {"placeholder":"Add hero content, which is typically an introductory area of a page accompanied by call to action or two."} -->
<p>test</p>
<!-- /wp:paragraph --><!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"placeholder":"Primary button…"} -->
<div class="wp-block-button"><a class="wp-block-button__link">test</a></div>
<!-- /wp:button --><!-- wp:button {"placeholder":"Secondary button…","className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link">test</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div></div></div>
<!-- /wp:coblocks/hero -->
```

**Comment by olafleur** [comment]
Oh, nice! Thanks a lot, I did not know about block deprecation! :)

**Pull request merged**
