### PR TITLE
Improve Shape Divider style previews for WordPress 5.3

### LINKED ISSUE #1090: ISBAT preview the Shape Divider block within style panels/dropdowns in WP 5.3
**Describe the bug**
While #1077 resolves the orientation for the #1043 issue, we need to resolve the scaling/display issues in WP 5.3 for the Shape Divider block. 

**Screenshots**
Screen Shot 2019-11-04 at 9 46 03 AM

**Expected behavior**
The dividers are clearly visible within both the Styles panel within the Settings Sidebar and the Styles dropdown within the block toolbar. 

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.3 RC

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any) 6.4+

### PR DESCRIPTION
**Pull request by jrtashjian**
Resolves #1090 

Removing a lot of the existing styles solved the problems we were having. WordPress 5.3 will bring new styles in the block style panel previews. We do need to fix some display issues here and because of that I was able to figure out a specific selector for Gutenberg 6.3 (when the new block preview styles were added) and after.

```
.block-editor-block-preview__content[style*="transform:"] {
    .wp-block-coblocks-shape-divider {
    }
}
```

**Style Previews with WordPress 5.2.4**

wordpress-5-2-4

**Style Previews with Gutenberg 6.3+**

gutenberg-6-8-0

### CODE REVIEW

**Comment by richtabor** [comment]
Here's the Block Styles panel with TwentyTwenty activated. I think some of this is how themes are manipulating the blocks within the editor. 
Screen Shot 2019-11-11 at 2 33 26 PM

**Comment by richtabor** [comment]
Here's what we get without any editor styles. 
Screen Shot 2019-11-11 at 2 34 34 PM

**Comment by jrtashjian** [comment]
Messages from Slack for reference:

> I’ve tested:
> 1. WP 5.2.4, with and without Gutenberg 6.8.0 active, with TwentyTwenty and with bare Underscores themes.
> 2. WP 5.3-RC3, with and without Gutenberg 6.8.0 active, with TwentyTwenty and with bare Underscores themes.
> 3. WP 5.4-alpha-46674 (WP nightly), with and without Gutenberg 6.8.0 active, with TwentyTwenty and with bare Underscores themes.
> I’m seeing consistent results to my screenshots in that PR

Screen Shot 2019-11-11 at 2 55 16 PM

Screen Shot 2019-11-11 at 2 55 35 PM

**Comment by jrtashjian** [comment]
Updated this PR with the latest from master. These are the browsers I've tested without any issues now running WordPress 5.2.3 without the Gutenberg plugin active:

- Chrome 79.0.3945.117
- Safari 13.0.4 (15608.4.9.1.3)
- Firefox 68.4.1esr

@richtabor @AnthonyLedesma @EvanHerman if either of you are still running into display issues can you debug a bit so we can keep moving this PR towards completion? If not you can just approve the PR and it will be merged in.

I'm removing it from today's release.

**Pull request merged**
