### PR TITLE
Use background image SVGs for the Food & Drinks block item attributes

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
Related to #455 

Food Item block refactor to use buttons with SVG background images similar to Social blocks. Assets, styles, and deprecations added to handle change. 

Tested and confirmed working with Chrome, FireFox, Safari, Edge, IE11, and Opera browsers.

foodItemAttributes

### CODE REVIEW

**Comment by AnthonyLedesma** [comment]
@richtabor Notice the button outlines in the Gif. I wanted to pass the outline to the inner span instead but could not get it right. Any suggestions? Here is what I was trying.
```scss
	&__attribute:focus {
		outline: none;
		span{
			outline-color:rgba(0, 0, 0, 0.847);
			outline-offset:0px;
			outline-style:solid;
			outline-width:0px;
		}
	}
```

**Comment by richtabor** [comment]
Can we tweak the icons to display inline again with the titles?
Screen Shot 2019-12-13 at 1 35 25 PM
Screen Shot 2019-12-13 at 1 35 19 PM

**Comment by richtabor** [comment]
Also, the active state should not turn the icon white. ScreenFlow

**Comment by AnthonyLedesma** [comment]
Looking better now @richtabor.

image

image

**Comment by AnthonyLedesma** [comment]
Implemented suggested improvements and tested deprecated functions and cross browsers. 

Confirmed working on Chrome, FireFox, Safari, Edge, IE11, and Opera browsers.

**Pull request merged**
