### PR TITLE
Fix CoBlocksFontSizePicker component

### PR DESCRIPTION
**Pull request by EvanHerman**
Resolves https://github.com/godaddy-wordpress/coblocks/issues/2173

### Description
This PR fixes the `CoBlocksFontSizePicker` component not updating the dropdown value to the correct selected value. This PR also allows users to switch back to `default`.

### Screenshots
image

image

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### How has this been tested?
Manually tested each block using the `CoBlocksFontSizePicker` component.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] I've included any necessary tests 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by olafleur-godaddy** [comment]
It seems to break the font size settings of the Highlight block, though :(

**Comment by EvanHerman** [comment]
@olafleur-godaddy You are right, I didn't see that. I'll take another look.

**Review by olafleur-godaddy — CHANGES_REQUESTED** [review]
The added Click To Tweet Cypress test does not seem to work on WP 5.9 beta 2

**Review by AnthonyLedesma — CHANGES_REQUESTED** [review]
There is a bit of strange behavior here. 

When setting the font size to `large` the FontSize controls instead set to `custom` with 26px value. This should show `large` instead.

When setting the font size to `custom` the label instead changes to `default` with no custom value set. Ideally, we should set a default custom value that allows the label to specify `custom` and still have a sample value for a user to modify.
FontSizeBugged

**Comment by snovosel** [comment]
@AnthonyLedesma I wasn't able to reproduce that functionality above regarding not being able to select named options:

https://user-images.githubusercontent.com/18115694/145290879-fbfb869a-3d5f-4206-bbc8-59a1a7429ad9.mov

However, I am able to reproduce the second comment as shown in the video. I've determined that the cause of this is due to the `<FontSizePicker />` core component which provides an `onChange` callback prop with a single argument. In both scenarios , the "Default" option and "Custom" option will pass `undefined` . On the other hand, the `<FontSizePicker />` component takes in a value which if `undefined` will display the "Default" option. I believe this is a bug in core and so can submit an issue .

Otherwise, the UX for this component has been updated in 5.9 and this is no longer an issue with the updated version.

**Comment by AnthonyLedesma** [comment]
Sounds good thanks for checking. I had a thought that It could be because we have different themes activated but I have not tested that yet.

**Comment by jonathanbardo** [comment]
@EvanHerman won't this PR basically remove the class name added when choosing from the Dropdown? eg `has-small-font`

**Review by olafleur-godaddy — APPROVED** [review]
Oh, the tests do not seem to be properly filtered on WP 5.8 and WP 5.9

**Review by olafleur-godaddy — APPROVED** [review]

**Review by AnthonyLedesma — APPROVED** [review]
The issue where the label does not show still exists. As expected this only affects core themes where TwentyTewnety is affected and possibly others. The case of a missing label is not a big deal for me given that the pixel value is shown regardless. No issues with deprecations were detected. LGTM.

**Pull request merged**
