### PR TITLE
Update Event Item icon

### PR DESCRIPTION
**Pull request by olafleur**
### Description
Change the icon of the event item.

### Screenshots
Before : 
Capture d’écran, le 2021-07-23 à 10 37 41

After : 
Capture d’écran, le 2021-07-23 à 10 37 05

### Types of changes
Visual change

### CODE REVIEW

**Comment by eherman-godaddy** [comment]
@olafleur I'm not seeing the icon on my end, any ideas why?
image

**Comment by olafleur** [comment]
Oh!

Did you do a `yarn install` before building it? I've changed the dependency version on coblocks-icons and the new icon is in the latest version.

But I'll re-test it to make sure that I did not break anything inadvertently.

**Comment by eherman-godaddy** [comment]
@olafleur Yeah I had to delete my `yarn.lock` file and remove `node_modules` then just `yarn install` again. I think the lock file was still referencing the older version.

Looks good on my end!
image

**Review by EvanHerman — APPROVED** [review]
Changes look good on my end 👍

**Pull request merged**
