### PR TITLE
refactor services block to use react hooks

### PR DESCRIPTION
**Pull request by snovosel**
### Description

This block already implements a functional component architecture. This PR is to remove the Fragment components from within the Services block and related components.

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by EvanHerman — CHANGES_REQUESTED** [review]
~Everything is working well here, the only thing that I'm noticing is that there is no way to specify an href attribute for the buttons beneath each service block, so if you display buttons beneath the service block it's just an `<a>` element with no href.~

**Review by EvanHerman — APPROVED** [review]
Disregard my last review. I overlooked the link icon in the toolbar. Things are looking good and working well on my end 👌

**Comment by eherman-godaddy** [comment]
@snovosel Fixed the e2e tests. Feel free to merge this whenever you feel comfortable doing so

**Comment by EvanHerman** [comment]
I'm going to merge this so we can get the e2e tests passing on all of the other PRs.

**Pull request merged**
