### PR TITLE
Use column and gutter utility classes within the Food and Drinks block

### LINKED ISSUE #662: ISBAT adjust the columns within the Food & Drinks block
**Is your feature request related to a problem? Please describe.**
It's currently not possible to set the column count within the Food & Drinks block. 

**Describe the solution you'd like**
I should be able to set the columns count between two and four columns. There is an existing attribute already present and a `data-columns` attribute already in place which can be leveraged.

### PR DESCRIPTION
**Pull request by jrtashjian**
### Description

The new utility classes for columns and gutters have been applied to the Food and Drinks block. This change includes two new controls in the block inspector to set columns from 2 to 4 (when the "grid" style is selected) as well as small, medium, large, xlarge gutter sizes.

### Screenshots

image

### Types of changes

- New block inspector control to select a number of columns
- New block inspector control to alter the spacing between columns (gutter)
- Deprecation to handle the removal of old column and spacing classes
- Improvements to helper functions related to Cypress end-to-end tests

### How has this been tested?

- Jest tests with snapshots have been added for the save function.
- Cypress end-to-end tests have been added.

### Checklist:

- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request 

Closes #662

### CODE REVIEW

**Comment by jrtashjian** [comment]
Good catch on the columns count and placeholder, I'll get a fix in for that. As for the buttons I had added styles for this but I probably need another breakpoint.

**Comment by jrtashjian** [comment]
@AnthonyLedesma the new styles you've added were causing the issue. The placeholder component has it's own breakpoints to handle it's own display at different sizes. I slimmed down the styles you added to just those that center aligned the placeholder icon, text, and buttons. This is what it looks like now:

Kapture 2020-03-24 at 12 02 30

**Comment by jrtashjian** [comment]
@AnthonyLedesma Layout fixes made and I've tested with the Gutenberg Starter Theme, TwentyTwenty, and Go.

E2E tests against Firefox are failing on Cypress for some reason but they are all passing when I run them locally (with WordPress 5.4 and Go). I'm confident merging this in even though the e2e-firefox job fails.

**Comment by AnthonyLedesma** [comment]
@jrtashjian Looks and works great! LGTM. The tests are failing for an unrelated reason and **DO** pass locally.

**Pull request merged**
