### PR TITLE
Only load front end CSS when it is needed

### PR DESCRIPTION
**Pull request by josephscott**
This checks to make sure that a Coblock is being used before requiring the CSS to be loaded on the front end of the site.  This is to address #1454 

In my basic tests this worked fine, however I'd like to see it get broader testing to make sure I haven't missed other conditions.

### CODE REVIEW

**Comment by richtabor** [comment]
Good stuff, we'll run it though some testing. I'll hand this to you @jrtashjian. Should work find, though we'll need to make sure the assets load on index/archive views.

**Comment by josephscott** [comment]
@richtabor  / @jrtashjian  - any thoughts on when this could be reviewed and included in a new release?

**Comment by jrtashjian** [comment]
Hey @josephscott, I’m planning to review this during the current release cycle. If all looks/works well (which at first glance it does) then it’ll make it into the release next Thursday.

**Comment by josephscott** [comment]
Sounds good!

**Comment by jrtashjian** [comment]
Closes #1454

**Pull request merged**
