### PR TITLE
Project Structure change

### PR DESCRIPTION
**Pull request by jonathanbardo**
### Description
- Move webpack back to the root. Developers were always confused about where it was. 
- Upgrade to Composer V2.
- Run php linting command inside docker (the phpunit docker keeps the wp-env php version

### CODE REVIEW

**Review by AnthonyLedesma — COMMENTED** [review]
Changes look good. I still need to get this tested locally because I usually don't use the wp-env containers.

**Comment by olafleur-godaddy** [comment]
Screen Shot 2022-01-13 at 10 11 59

When running `yarn lint:php` I have this error message

**Comment by olafleur-godaddy** [comment]
Screen Shot 2022-01-13 at 10 13 28

This when running `yarn php:composer:install`

I am probably missing something ;)

**Comment by olafleur-godaddy** [comment]
Oh, should I switch to Composer 2 to run this?

**Review by olafleur — APPROVED** [review]

**Pull request merged**
