### PR TITLE
Refactor the form radio and checkbox labels

### PR DESCRIPTION
**Pull request by EvanHerman**
# Description
Refactor the CoBlocks form block labels so that we can style them easier within Go.

**Related PR:** https://github.com/godaddy-wordpress/go/pull/477

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by richtabor** [comment]
We need to tweak the default layout styling (with no theme styles applied)

Screen Shot 2020-03-09 at 6 02 36 PM

**Comment by richtabor** [comment]
Should look like this (unless the inline checkbox ToggleControl is enabled): 

Screen Shot 2020-03-09 at 6 06 55 PM

**Comment by EvanHerman** [comment]
Not sure why all of the e2e tests are running but the Galleries tests are failing because we've renamed CoBlocks Galleries to just Galleries.

We will probably have to merge this and then loop back around and fix the tests, or figure out why all of the `e2e` tests are running on this PR/branch.

**Comment by EvanHerman** [comment]
Scratch the above comment. Just needed a rebase with master to properly detect the changed files. 🤓

**Pull request merged**
