### PR TITLE
Convert social-share block to Social Links block

### LINKED ISSUE #466: ISBAT re-order social icons in the Share block
The [Contact Widgets plugin](https://wordpress.org/plugins/contact-widgets/) has an interesting UI where users can drag to organize the activated icons how they see fit. It'd be interesting to apply that same technique to our Social block.

ScreenFlow

I think it'd be interesting if we could make the icons the draggable components.

### PR DESCRIPTION
**Pull request by jrtashjian**
### Description
Deprecates our social-share block for the core/social-links block. Sharing urls are migrated to the new block and an extension added to the core/social-links block to allow these urls to be generated automatically.

Resolves #466

### Types of changes
New feature

### How has this been tested?
Automated testing

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Comment by jrtashjian** [comment]
The remaining issues have been fixed.

Here's the before with `coblocks/social`:

image

And after with `core/social-links`:

image

Visual labels on the buttons are not supported with the core block. Also, If a background color was applied to the `coblocks/social` block we will wrap the new `core/social-links` block with a `core/group` that handles the added background color and padding.

**Comment by olafleur-godaddy** [comment]
Good job!

**Comment by jonathanbardo** [comment]
@jrtashjian

**Review by jonathanbardo — APPROVED** [review]

**Review by AnthonyLedesma — APPROVED** [review]
LGTM

**Pull request merged**
