### PR TITLE
add default align property to gallery collage block

### PR DESCRIPTION
**Pull request by snovosel**
### Description
Sets align attribute to wide as default on gallery collage block

### Types of changes

Enhancement

### How has this been tested?
visually tested

### Checklist:
- [x] My code is tested
- [x] My code follows accessibility standards 
- [x] My code has proper inline documentation 
- [x] I've included any necessary tests 
- [x] I've included developer documentation 
- [x] I've added proper labels to this pull request

### CODE REVIEW

**Review by AnthonyLedesma — APPROVED** [review]
No deprecation needed. The block is automatically updated to use the new default alignment if it has not previously been configured by a user. This means that existing blocks with images but have not yet been aligned by a user will still be upgraded to the new default width upon loading the editor. 

LGTM.

**Review by AnthonyLedesma — CHANGES_REQUESTED** [review]
Actually, I realize that this change causes default markup for the collage gallery to differ from previous iterations. We need to update Jest test snapshots here I think and possibly modify some tests.

**Comment by snovosel** [comment]
@AnthonyLedesma updating snapshots seem to have fixed the test issues. Was there anything else that should to be updated?

**Review by AnthonyLedesma — APPROVED** [review]
LGTM

**Pull request merged**
